# Generated by Django 3.2.8 on 2021-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/img/images'),
        ),
    ]
